In [3]:
import pandas as pd
import pymongo

df = pd.read_csv('consumer_electronics_sales_data.csv')
df.head()

,ProductID,ProductCategory,ProductBrand,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent
0,5874,Smartphones,Other Brands,312.949668,18,0,2,1,0
1,5875,Smart Watches,Samsung,980.389404,35,1,7,2,1
2,5876,Tablets,Samsung,2606.718293,63,0,1,5,1
3,5877,Smartphones,Samsung,870.395450,63,1,10,3,1
4,5878,Tablets,Sony,1798.955875,57,0,17,3,0

In [ ]:
# load environment variables
import os
from dotenv import load_dotenv

load_dotenv()

CONNECTION_STRING = os.getenv('CONNECTION_STRING')
DATABASE_NAME = os.getenv('DATABASE_NAME')
COLLECTION_NAME = os.getenv('COLLECTION_NAME')

In [4]:
# loading data to mongo db

client = pymongo.MongoClient(CONNECTION_STRING)
database = client[DATABASE_NAME]
collection = database[COLLECTION_NAME]

# converting df to list of dicts for entry into mongo db
data = df.to_dict(orient='records')

# inserting data to mongodb
collection.insert_many(data)

In [6]:
fetched_df = pd.DataFrame(list(collection.find()))
fetched_df.head(2)

,_id,ProductID,ProductCategory,ProductBrand,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent
0,6ab811cf78999c030e477356,5874,Smartphones,Other Brands,312.949668,18,0,2,1,0
1,6ab811cf78999c030e477357,5875,Smart Watches,Samsung,980.389404,35,1,7,2,1